spring:
  datasource:
    username: wzz
    password: wzz0504
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.117.180.137:3306/ape_frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 50
      min-idle: 20
      max-active: 200
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
sql:
  beauty:
    show: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_falg
      logic-delete-value: 1
      logic-not-delete-value: 0
swagger:
  base-package: com.psj.user
  title: ape-frame
  description: 一个脚手架
  contactEmail: 1503667055@163.com
  contactName: pengshj
  contactUrl: 123
  version: 1.0
  group-name: 用户模块