spring:
  port: 8081
  datasource:
    username: psj
    password: Wzz980504
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp1w1o668ez79qx0fgo.mysql.rds.aliyuncs.com:3306/ape_frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 200
      max-wait: 60000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
  redis:
    host: 121.43.225.182
    port: 6379
    password: Redis123
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0

sql:
  beauty:
    show: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delete_falg
      logic-delete-value: 1
      logic-not-delete-value: 0
swagger:
  base-package: com.psj.user
  title: ape-frame
  description: 一个脚手架
  contactEmail: 1503667055@163.com
  contactName: pengshj
  contactUrl: 1
  version: 1.0
  group-name: 用户模块
logging:
  config: classpath:log4j-spring.xml
log:
  aspect:
    enable: true
guava:
  cache:
    switch: true

#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:9000/xxl-job-admin
#    accessToken: default_token
#    executor:
#      appname: ape-frame
#      address:
#      ip: 127.0.0.1
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30